apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-m8nj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-m8nj@sha256:9a3c9ebc0f46e02032067a0d0b1f306b9f09478be094454c403d4dc759d66cd0
        name: my-nodejs
        resources: {}
status: {}
